# Service for Streamlit UI Application
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/instance: test-llamastack-26012903
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-llamastack-26012903
  name: test-llamastack-26012903
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
      name: http
  selector:
    app.kubernetes.io/instance: test-llamastack-26012903

