apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: test-llamastack-26012903
  janus-idp.io/tekton: test-llamastack-26012903
  backstage.io/kubernetes-id: test-llamastack-26012903
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: test-llamastack-26012903
resources:
  - application-dev.yaml
